"""fix: create colum status

Revision ID: c6e4f3b7b44b
Revises: 48177af17256
Create Date: 2025-01-21 21:08:55.934383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e4f3b7b44b'
down_revision: Union[str, None] = '48177af17256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('status', sa.Enum('pending', 'approved', 'denied', name='requeststatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'status')
    # ### end Alembic commands ###
